In [10]:
import numpy as np
x = np.random.randint(1,100,(4, 4))
print(x)

[[19 92 89 15]
 [24 80  8 56]
 [ 3 49 71 89]
 [50 32 67 49]]


In [4]:
# sum of all values
total = x.sum() # or np.sum(x)
print(total)
#sum of each column
col_total = x.sum(axis=0) # or np.sum(x,axis = 0)
print(col_total)
# sum of all rows
row_total = x.sum(axis=1) # or np.sum(x,axis = 1)
print(row_total)

1193
[216 265 177 141 211 183]
[322 212 285 374]


In [6]:
median = np.median(x)
print(median)

48.5


In [7]:
print(np.sin(x))

[[-0.96611777  0.0353983  -0.64353813  0.83665564  0.98662759  0.1673557 ]
 [ 0.84147098  0.92002604 -0.00885131 -0.90557836 -0.96611777  0.74511316]
 [ 0.99287265  0.55142668  0.74511316  0.82682868  0.39592515 -0.64353813]
 [ 0.98358775 -0.62988799  0.51397846 -0.40403765  0.85090352 -0.83177474]]


In [9]:
x.prod() # product of all values



0

In [11]:
np.linalg.det(x)

30789632.000000022

In [16]:
y = np.random.randint(0,10,(5,5))
print(y)
print('checkin if there is no zeros in the matrix')
print(np.all(y)) # or y.all()

[[6 3 4 4 5]
 [7 4 2 9 5]
 [7 7 5 8 4]
 [3 4 7 5 9]
 [8 2 7 5 9]]
checkin if there is no zeros in the matrix
True


In [19]:
z = np.random.choice([0,1,0,0],(3,3))
print(z)
print('checking if there is atleast one -/+ value in the matrix')
print(z.any())

[[0 1 0]
 [0 0 0]
 [0 1 0]]
checking if there is atleast one -/+ value in the matrix
True


In [23]:
x = np.random.randint(1,10,(4, 4))
print('shape',x.shape)
print('x')
print(x)
x = x.T # transpose
print('x transposed')
print(x)
x = x.flatten()
print('x flattened')
print(x)

shape (4, 4)
x
[[3 8 7 1]
 [6 1 7 5]
 [7 2 3 2]
 [6 4 7 2]]
x transposed
[[3 6 7 6]
 [8 1 2 4]
 [7 7 3 7]
 [1 5 2 2]]
x flattened
[3 6 7 6 8 1 2 4 7 7 3 7 1 5 2 2]


In [25]:
x.reshape(2,8)

array([[3, 6, 7, 6, 8, 1, 2, 4],
       [7, 7, 3, 7, 1, 5, 2, 2]])

In [26]:
x.reshape(1,1,1,1,2,8)

array([[[[[[3, 6, 7, 6, 8, 1, 2, 4],
           [7, 7, 3, 7, 1, 5, 2, 2]]]]]])

# slicing and filtering

In [32]:
y = np.random.randint(1,10,(4, 4))
print(y.ndim,'dimension')
print(y.size,'elements')
print(y)
print('firstrow',y[0])
print('lastrow',y[-1])

2 dimension
16 elements
[[6 2 5 7]
 [8 2 5 9]
 [3 5 9 3]
 [8 6 9 2]]
firstrow [6 2 5 7]
lastrow [8 6 9 2]


In [41]:
# slicing for 2d object
# arr[row,col]
print('first column\n',y[:,0])
print('last column\n',y[:,-1])
print('first 3 columns\n',y[:,:3])
print('last 4 columns\n',y[:,-4:])

first column
 [6 8 3 8]
last column
 [7 9 3 2]
first 3 columns
 [[6 2 5]
 [8 2 5]
 [3 5 9]
 [8 6 9]]
last 4 columns
 [[6 2 5 7]
 [8 2 5 9]
 [3 5 9 3]
 [8 6 9 2]]
